# Generated by Django 5.2.3 on 2025-08-19 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion',
        ),
    ]
