# Generated by Django 5.2.1 on 2025-09-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_remove_proveedor_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='representante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
