# Generated by Django 5.2.1 on 2025-09-27 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('productos', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_productos', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('empaquetado', 'Empaquetado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=20)),
            ],
        ),
    ]
