# Generated by Django 5.2.3 on 2025-09-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_productos', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
