# Generated by Django 5.2.3 on 2025-09-11 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total_productos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
    ]
