# Generated by Django 5.2.3 on 2025-09-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedido_fecha_creacion_remove_pedido_mensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_productos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
