# Generated by Django 5.2.3 on 2025-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_total_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('empaquetado', 'Empaquetado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=20),
        ),
    ]
