# Generated by Django 5.2.1 on 2025-09-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word DOC'), ('docx', 'Word DOCX'), ('xls', 'Excel XLS'), ('xlsx', 'Excel XLSX'), ('jpg', 'Imagen JPG'), ('jpeg', 'Imagen JPEG'), ('png', 'Imagen PNG')], max_length=10)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
